name:                simple-tope-visualizer
version:             0.1.0
github:              "pptx704/simple-tope-visualizer"
license:             BSD3
author:              "Md Motasim Bhuiyan"
maintainer:          "rafeedm.bhuiyan@gmail.com"
copyright:           "2022 Md Motasim Bhuiyan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pptx704/simple-tope-visualizer#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- codeworld-api
- simple-topes
- text

library:
  source-dirs: src

executables:
  simple-tope-visualizer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-topes
    - simple-tope-visualizer
